# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.4
  - 1.5
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  exclude:
    - arch: x86
      os: osx
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
      CODECOV_TOKEN="17ae06a7-b36c-403c-b6e0-d044aded3a97"
      bash <(curl -s https://codecov.io/bash)
